FROM node:16-alpine

ENV NODE_ENV=development
ENV npm_config_yes=true

RUN apk --no-cache add --virtual .builds-deps build-base python3 bash libnss3-tools

RUN wget -O mkcert "https://dl.filippo.io/mkcert/latest?for=linux/amd64" \
&& chmod +x mkcert \
&& cp mkcert /usr/local/bin/mkcert \
&& mkdir -p $HOME/.simulacrum/certs \
&& cd $HOME/.simulacrum/certs \
&& mkcert -install \
&& cat /root/.local/share/mkcert/rootCA.pem >> /etc/ssl/certs/ca-certificates.crt \
&& mkcert localhost

WORKDIR /simulacrum

EXPOSE 4000

COPY "package.json" .
COPY "package-lock.json" .
COPY "tsconfig.packages.json" .
COPY "tsconfig.base.json" .

COPY packages/server packages/server
COPY packages/client packages/client
COPY packages/ui packages/ui
COPY packages/auth0 packages/auth0

RUN npm install --location=global npm@7.19.1
RUN npm ci

RUN npm run build

CMD ["npx", "@simulacrum/auth0-simulator"]