FROM node:16-alpine

ENV NODE_ENV=development
ENV npm_config_yes=true

RUN apk --no-cache add --virtual .builds-deps build-base python3 bash

WORKDIR /simulacrum

EXPOSE 4000

COPY "package.json" .
COPY "package-lock.json" .
COPY "tsconfig.packages.json" .
COPY "tsconfig.base.json" .

COPY packages/server packages/server
COPY packages/client packages/client
COPY packages/ui packages/ui
COPY packages/auth0 packages/auth0

RUN npm install --location=global npm@7.19.1
RUN npm ci

RUN npm run build

CMD ["npx", "@simulacrum/auth0-simulator"]